<head>



    <!-- <link rel="stylesheet" type="text/css" href="slick/slick.css"/> -->
    <!-- // Add the new slick-theme.css if you want the default styling -->
    <!-- <link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/> -->


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer" />    
</head>

    
    
<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script> -->
    <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script> -->
    <!-- <script type="text/javascript" src="slick/slick.min.js"></script> -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.js" integrity="sha512-WNZwVebQjhSxEzwbettGuQgWxbpYdoLf7mH+25A7sfQbbxKeS5SQ9QBf97zOY4nOlwtksgDA/czSTmfj4DUEiQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <ul class="testslick max-w-[1170px] mx-auto py-[150px] bg-[#f5f4f2]">
    <li class="slick-item ">
    <h2 class="text-center text-[33px] font-oswald font-semibold tracking-wide mb-[60px]">FROM OUR BLOG</h2>
<div class ="blog-content flex items-center justify-center max-w-[900px] mx-auto ">
    <div class="blog-image mr-8 w-1/2"><img class="h-[250px] float-right" src="<?php echo $this->getViewFileUrl('images/blog-1.jpg'); ?>" alt ="blog-1" /></div>
    <div class="blog-info w-1/2">
         <h3 class="post-title text-3xl font-oswald my-[10px]"><a href="#">How to wear prints in winter</a></h3>
         <div class="post-date text-[14px]">Feb 12, 2017</div>
         <div class="short-desc text-[14px] mt-[20px]">Integer scelerisque diam vitae aliquam fringilla. In vitae eros ac libero mattis molestie nec in magna...</div>
         <button class="bg-black text-white  h-10 px-7 mt-[25px]">READ MORE</button>
    </div>

</div>
    </li>
    <li class="slick-item ">
    <h2 class="text-center text-[33px] font-oswald font-semibold tracking-wide mb-[60px]">FROM OUR BLOG</h2>
<div class ="blog-content flex items-center justify-center max-w-[900px] mx-auto ">
    <div class="blog-image mr-8 w-1/2"><img class="h-[250px] float-right" src="<?php echo $this->getViewFileUrl('images/blog-2.jpg'); ?>" alt ="blog-1" /></div>
    <div class="blog-info w-1/2">
         <h3 class="post-title text-3xl font-oswald my-[10px]"><a href="#">How to wear prints in winter</a></h3>
         <div class="post-date text-[14px]">Feb 12, 2017</div>
         <div class="short-desc text-[14px] mt-[20px]">Integer scelerisque diam vitae aliquam fringilla. In vitae eros ac libero mattis molestie nec in magna...</div>
         <button class="bg-black text-white  h-10 px-7 mt-[25px]">READ MORE</button>
    </div>

</div>
    </li>
    
    

    </ul>

    <script>
    $('.testslick').slick({
    infinite: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    accessibility: true,
    arrows : true,
   
    });
</script>